### ISSUE TITLE
Incompatibility with Drupal less than 8.5

### ISSUE THREAD

**Issue by kolesnikoff** [jorgik1/social_feed_fetcher#1]
Hi Yuriy,
The latest commits with adding Messenger service broke the compatibility with older versions of Drupal, as far as this service was introduced into 8.5.
Could you set the minimal required Drupal version in composer.json or revert the latest changes?
Thank you

**Comment by jorgik1** [comment]
Hi Alex, thank you. I will revert messenger service drupal set messgae.
